[package]
name = "vise-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
vise-ast.workspace = true
vise-check.workspace = true
vise-diag.workspace = true

[dev-dependencies]
vise-parse.workspace = true
vise-interp.workspace = true

[lints]
workspace = true
