//! The C backend.
//!
//! Vise is lowered to C rather than to machine code. C is the most portable
//! assembler available, every platform has an optimiser for it, and the whole
//! backend fits in one file that a reader can check against the language it
//! implements.
//!
//! There is no intermediate representation. One earns its place when there are
//! several backends or optimisation passes; with one backend it is indirection,
//! and it can be introduced later without disturbing the front end.
//!
//! # What this backend does not do yet
//!
//! Each of these is refused with a diagnostic naming it, never miscompiled:
//! generic functions and generic records (no monomorphisation), borrows,
//! method calls, `Map` and `Set`, and calls to imported functions, which have
//! no definition to emit.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use vise_ast::{
    BinOp, Binding, Block, Effect, Expr, ExprKind, FnDecl, ItemKind, Literal, Module, Pattern,
    PatternKind, Stmt, StmtKind, StrPart, UnOp,
};
use vise_check::{Ty, TypeMap};
use vise_diag::{Code, Diagnostic, Span};

/// The result of lowering a module.
#[derive(Debug)]
pub struct Emitted {
    /// C source, ready for a compiler.
    pub c_source: String,
    /// Constructs this backend cannot lower yet.
    pub unsupported: Vec<Diagnostic>,
}

impl Emitted {
    #[must_use]
    pub fn is_complete(&self) -> bool {
        self.unsupported.is_empty()
    }
}

/// Lower `module` to C, using the types the checker inferred.
#[must_use]
pub fn emit(module: &Module, types: &TypeMap) -> Emitted {
    let mut e = Emitter {
        types,
        records: BTreeMap::new(),
        enums: BTreeMap::new(),
        variant_tags: BTreeMap::new(),
        variant_payloads: BTreeMap::new(),
        distinct: BTreeMap::new(),
        functions: BTreeMap::new(),
        lines: Vec::new(),
        depth: 1,
        next_temp: 0,
        unsupported: Vec::new(),
    };
    let c_source = e.module(module);
    Emitted {
        c_source,
        unsupported: e.unsupported,
    }
}

/// Slots in the runtime's `vise_enum`, from `runtime/c/value.h`.
const MAX_ENUM_FIELDS: usize = 8;

/// Built-in enums, which have no declaration to read.
const BUILTIN_VARIANTS: &[(&str, &str, usize)] = &[
    ("Ok", "Result", 1),
    ("Err", "Result", 1),
    ("Some", "Option", 1),
    ("None", "Option", 0),
];

struct Emitter<'a> {
    types: &'a TypeMap,
    /// Record name to its fields, in declaration order.
    records: BTreeMap<String, Vec<(String, Ty)>>,
    /// Enum name to its variant names.
    enums: BTreeMap<String, Vec<String>>,
    /// Variant name to (enum name, tag).
    variant_tags: BTreeMap<String, (String, u32)>,
    /// Variant name to the types of its payload fields.
    variant_payloads: BTreeMap<String, Vec<Ty>>,
    /// `type X = Y` erases to Y at runtime.
    distinct: BTreeMap<String, String>,
    functions: BTreeMap<String, FnDecl>,
    lines: Vec<String>,
    depth: usize,
    next_temp: u32,
    unsupported: Vec<Diagnostic>,
}

impl Emitter<'_> {
    fn refuse(&mut self, span: Span, what: &str) {
        self.unsupported.push(
            Diagnostic::error(
                Code::UnexpectedToken,
                span,
                format!("the C backend cannot lower {what} yet"),
            )
            .with_note("`vise run` interprets the same program without this restriction"),
        );
    }

    // --- module ----------------------------------------------------------

    fn module(&mut self, module: &Module) -> String {
        self.collect(module);

        let mut out = String::new();
        out.push_str("/* Generated by vise. Do not edit. */\n#include \"value.h\"\n\n");

        // Records become plain structs; their fields are already monomorphic.
        for (name, fields) in &self.records.clone() {
            let _ = writeln!(out, "typedef struct {{");
            for (field, ty) in fields {
                let _ = writeln!(out, "    {} {};", self.c_type(ty), mangle(field));
            }
            let _ = writeln!(out, "}} vise_rec_{name};\n");
        }

        // `vise_enum` is declared in value.h with a fixed width, so the
        // runtime can return a Result without depending on this program's
        // types. A variant too wide for it is refused rather than truncated.
        // Counted in slots, not in fields: a string field takes two of them.
        let payloads: Vec<Vec<Ty>> = self.variant_payloads.values().cloned().collect();
        let widest = payloads
            .iter()
            .map(|fields| fields.iter().map(|t| self.slot_width(t)).sum::<usize>())
            .max()
            .unwrap_or(0);
        if widest > MAX_ENUM_FIELDS {
            self.unsupported.push(
                Diagnostic::error(
                    Code::UnexpectedToken,
                    Span::new(vise_diag::FileId(0), 0, 0),
                    format!(
                        "an enum variant needing {widest} payload slots; the backend supports up to \
                         {MAX_ENUM_FIELDS}"
                    ),
                )
                .with_note("`vise run` interprets the same program without this limit"),
            );
        }

        for (variant, (owner, tag)) in &self.variant_tags {
            let _ = writeln!(out, "#define VISE_TAG_{owner}_{variant} {tag}u");
        }
        // The runtime builds `Ok`, `Err`, `Some`, and `None` itself, so its
        // tags and these must be the same numbers. Checking it here means a
        // divergence is a compile error rather than a wrong branch at runtime.
        out.push_str(concat!(
            "\n_Static_assert(VISE_TAG_Result_Ok == VISE_TAG_OK, \"tags must agree\");\n",
            "_Static_assert(VISE_TAG_Result_Err == VISE_TAG_ERR, \"tags must agree\");\n",
            "_Static_assert(VISE_TAG_Option_Some == VISE_TAG_SOME, \"tags must agree\");\n",
            "_Static_assert(VISE_TAG_Option_None == VISE_TAG_NONE, \"tags must agree\");\n\n"
        ));

        for name in self.functions.keys().cloned().collect::<Vec<_>>() {
            let decl = self.functions[&name].clone();
            let _ = writeln!(out, "{};", self.signature(&decl));
        }
        out.push('\n');

        for name in self.functions.keys().cloned().collect::<Vec<_>>() {
            let decl = self.functions[&name].clone();
            out.push_str(&self.function(&decl));
            out.push('\n');
        }

        // A C `main` that runs the Vise one and releases the arena.
        let has_main = self.functions.contains_key("main");
        if has_main {
            out.push_str("int main(int argc, char **argv) {\n");
            out.push_str("    vise_set_args(argc, argv);\n");
            out.push_str("    (void)vise_fn_v_main();\n");
            out.push_str("    vise_runtime_shutdown();\n    return 0;\n}\n");
        }
        out
    }

    fn collect(&mut self, module: &Module) {
        for (variant, owner, arity) in BUILTIN_VARIANTS {
            let tag = u32::try_from(self.variant_tags.len()).unwrap_or(0);
            self.variant_tags
                .insert((*variant).to_owned(), ((*owner).to_owned(), tag));
            // The payload of a built-in is generic, so its slot is decided at
            // each use rather than here.
            self.variant_payloads
                .insert((*variant).to_owned(), vec![Ty::Error; *arity]);
        }

        for item in &module.items {
            match &item.kind {
                ItemKind::Type(d) => {
                    if let vise_ast::TypeKind::Named { name, args } = &d.underlying.kind
                        && args.is_empty()
                    {
                        self.distinct.insert(d.name.name.clone(), name.name.clone());
                    }
                }
                ItemKind::Record(d) => {
                    if !d.generics.is_empty() {
                        self.refuse(d.span, "a generic record");
                        continue;
                    }
                    let fields = d
                        .fields
                        .iter()
                        .map(|f| (f.name.name.clone(), ty_of(&f.ty)))
                        .collect();
                    self.records.insert(d.name.name.clone(), fields);
                }
                ItemKind::Enum(d) => {
                    if !d.generics.is_empty() {
                        self.refuse(d.span, "a generic enum");
                        continue;
                    }
                    let mut names = Vec::new();
                    for v in &d.variants {
                        let tag = u32::try_from(self.variant_tags.len()).unwrap_or(0);
                        self.variant_tags
                            .insert(v.name.name.clone(), (d.name.name.clone(), tag));
                        self.variant_payloads.insert(
                            v.name.name.clone(),
                            v.fields.iter().map(|f| ty_of(&f.ty)).collect(),
                        );
                        names.push(v.name.name.clone());
                    }
                    self.enums.insert(d.name.name.clone(), names);
                }
                ItemKind::Fn(d) => {
                    if !d.generics.is_empty() {
                        self.refuse(d.span, "a generic function");
                        continue;
                    }
                    self.functions.insert(d.name.name.clone(), (**d).clone());
                }
            }
        }
    }

    // --- types -----------------------------------------------------------

    /// The C type for a Vise type.
    fn c_type(&mut self, ty: &Ty) -> String {
        match ty {
            Ty::Con(name, args) => match name.as_str() {
                "Int" => "int64_t".to_owned(),
                "Float" => "double".to_owned(),
                "Bool" => "bool".to_owned(),
                "Char" => "uint32_t".to_owned(),
                "Str" => "vise_str".to_owned(),
                // Unit carries no information, but C needs something to store.
                "Unit" => "int64_t".to_owned(),
                "List" => "vise_list".to_owned(),
                "Result" | "Option" => "vise_enum".to_owned(),
                "Map" | "Set" => "vise_list".to_owned(),
                _ if self.records.contains_key(name) => format!("vise_rec_{name}"),
                _ if self.enums.contains_key(name) => "vise_enum".to_owned(),
                // A distinct type is erased: `type UserId = Int` is an Int at
                // runtime, and the distinction has already done its work in the
                // checker.
                _ if self.distinct.contains_key(name) => {
                    let base = self.distinct[name].clone();
                    self.c_type(&Ty::Con(base, args.clone()))
                }
                _ => "int64_t".to_owned(),
            },
            // Borrows are refused before reaching here.
            Ty::Ref { inner, .. } => self.c_type(inner),
            Ty::Var(_) | Ty::Error => "int64_t".to_owned(),
        }
    }

    /// The union member a value of this type occupies inside a list slot.
    fn slot_member(&mut self, ty: &Ty) -> &'static str {
        match self.c_type(ty).as_str() {
            "int64_t" => "as_int",
            "double" => "as_float",
            "bool" => "as_bool",
            "uint32_t" => "as_char",
            // Anything larger than a slot lives on the heap. A list is indexed
            // by element, so its slots must all be one width; an enum payload
            // is not, and `slot_width` lets those spread instead.
            _ => "as_ptr",
        }
    }

    /// How many payload slots a value of this type occupies inside an enum.
    ///
    /// A string and a list are each a pointer and a length, so they take two.
    /// Spreading them is what keeps `Err("...")` from allocating: boxing one
    /// value per construction is the single most expensive thing this backend
    /// used to do -- on a loop returning fifty million `Result<Int, Str>`, the
    /// box cost 0.25s and 383MB against 0.04s and 11MB without it.
    fn slot_width(&mut self, ty: &Ty) -> usize {
        match self.c_type(ty).as_str() {
            "vise_str" | "vise_list" => 2,
            _ => 1,
        }
    }

    /// The payload slot a variant's field `index` begins at.
    fn field_slot(&mut self, variant: &str, index: usize, subject: &Ty) -> usize {
        (0..index)
            .map(|i| {
                let ty = self.payload_type(variant, i, subject);
                self.slot_width(&ty)
            })
            .sum()
    }

    /// Read a variant's field out of an enum, as an expression.
    ///
    /// A wide field is copied out with `memcpy` rather than read through a cast
    /// pointer, because a cast would read a `vise_str` through a `vise_slot`,
    /// which the aliasing rules do not allow. The optimiser turns the copy back
    /// into register moves.
    fn load_field(&mut self, subject: &str, offset: usize, ty: &Ty) -> String {
        let c_ty = self.c_type(ty);
        if self.slot_width(ty) == 1 {
            let member = self.slot_member(ty);
            return unpack(&c_ty, member, &format!("{subject}.f[{offset}]"));
        }
        let out = self.temp();
        self.line(format!("{c_ty} {out};"));
        self.line(format!(
            "memcpy(&{out}, &{subject}.f[{offset}], sizeof {out});"
        ));
        out
    }

    /// Write a value into a variant's field.
    fn store_field(&mut self, dest: &str, offset: usize, ty: &Ty, value: &str) {
        if self.slot_width(ty) == 1 {
            let member = self.slot_member(ty);
            let packed = self.pack(ty, value);
            self.line(format!("{dest}.f[{offset}].{member} = {packed};"));
            return;
        }
        let c_ty = self.c_type(ty);
        let held = self.temp();
        self.line(format!("{c_ty} {held} = {value};"));
        self.line(format!(
            "memcpy(&{dest}.f[{offset}], &{held}, sizeof {held});"
        ));
    }

    fn type_of(&self, e: &Expr) -> Ty {
        self.types
            .get(&(e.span.start, e.span.end))
            .cloned()
            .unwrap_or(Ty::Error)
    }

    fn signature(&mut self, f: &FnDecl) -> String {
        let ret = match &f.ret {
            Some(t) => self.c_type(&ty_of(t)),
            // A Unit-returning function still returns a value in C: lowering it
            // to `void` meant a call to it could not be assigned to the temporary
            // that an `if` or `match` used as an expression needs.
            None => "int64_t".to_owned(),
        };
        let mut params = Vec::new();
        for p in &f.params {
            let ty = ty_of(&p.ty);
            params.push(format!("{} {}", self.c_type(&ty), mangle(&p.name.name)));
        }
        let list = if params.is_empty() {
            "void".to_owned()
        } else {
            params.join(", ")
        };
        format!("{ret} vise_fn_{}({list})", mangle(&f.name.name))
    }

    // --- emission helpers ------------------------------------------------

    fn line(&mut self, text: impl AsRef<str>) {
        let mut s = String::new();
        for _ in 0..self.depth {
            s.push_str("    ");
        }
        s.push_str(text.as_ref());
        self.lines.push(s);
    }

    /// Put a value into a slot, moving it to the heap if it does not fit.
    ///
    /// Boxing emits a statement rather than an expression, because a C compound
    /// literal `(T){v}` initialises T's *first member* rather than the whole
    /// value, which silently produces the wrong struct.
    fn pack(&mut self, ty: &Ty, value: &str) -> String {
        let member = self.slot_member(ty);
        if member != "as_ptr" {
            return value.to_owned();
        }
        let c_ty = self.c_type(ty);
        let boxed = self.temp();
        self.line(format!("{c_ty} *{boxed} = vise_alloc(sizeof({c_ty}));"));
        self.line(format!("*{boxed} = {value};"));
        boxed
    }

    fn temp(&mut self) -> String {
        self.next_temp += 1;
        format!("t{}", self.next_temp)
    }

    /// Run `f` with a fresh line buffer, returning what it emitted.
    fn capture<T>(&mut self, f: impl FnOnce(&mut Self) -> T) -> (Vec<String>, T) {
        let saved = std::mem::take(&mut self.lines);
        let value = f(self);
        let captured = std::mem::replace(&mut self.lines, saved);
        (captured, value)
    }

    // --- functions -------------------------------------------------------

    fn function(&mut self, f: &FnDecl) -> String {
        let signature = self.signature(f);
        self.lines.clear();
        self.depth = 1;
        self.next_temp = 0;

        // §10: contracts are runtime checks.
        for clause in &f.requires {
            let c = self.expr(clause);
            self.line(format!(
                "if (!({c})) vise_trap(\"a `requires` clause of `{}` does not hold\");",
                f.name
            ));
        }

        let value = self.block(&f.body);
        let returns = f.ret.is_some();

        if returns {
            let ret_ty = self.c_type(&ty_of(f.ret.as_ref().expect("checked")));
            self.line(format!("{ret_ty} vise_result = {value};"));
            for clause in &f.ensures {
                let c = self.expr(clause);
                self.line(format!(
                    "if (!({c})) vise_trap(\"an `ensures` clause of `{}` does not hold\");",
                    f.name
                ));
            }
            self.line("return vise_result;");
        } else {
            self.line(format!("(void)({value});"));
            self.line("return 0;");
        }

        let mut out = format!("{signature} {{\n");
        for line in &self.lines {
            let _ = writeln!(out, "{line}");
        }
        out.push_str("}\n");
        out
    }

    /// Emit a block's statements and return a C expression for its value.
    fn block(&mut self, b: &Block) -> String {
        for s in &b.stmts {
            self.stmt(s);
        }
        match &b.tail {
            Some(t) => self.expr(t),
            None => "0".to_owned(),
        }
    }

    fn stmt(&mut self, s: &Stmt) {
        match &s.kind {
            StmtKind::Let { name, value, .. } => {
                let ty = self.type_of(value);
                let c_ty = self.c_type(&ty);
                let v = self.expr(value);
                match name {
                    Binding::Name(ident) => {
                        self.line(format!("{c_ty} {} = {v};", mangle(&ident.name)));
                    }
                    // `let _ =` still evaluates, for the effects.
                    Binding::Wildcard(_) => self.line(format!("(void)({v});")),
                }
            }
            StmtKind::Assign { target, value } => {
                let v = self.expr(value);
                let t = self.expr(target);
                self.line(format!("{t} = {v};"));
            }
            StmtKind::For {
                binding,
                iter,
                body,
            } => {
                let seq = self.expr(iter);
                let list = self.temp();
                let index = self.temp();
                self.line(format!("vise_list {list} = {seq};"));
                self.line(format!(
                    "for (int64_t {index} = 0; {index} < {list}.len; {index}++) {{"
                ));
                self.depth += 1;
                if let Binding::Name(ident) = binding {
                    let element = element_type(&self.type_of(iter));
                    let c_ty = self.c_type(&element);
                    let member = self.slot_member(&element);
                    let value = unpack(&c_ty, member, &format!("{list}.items[{index}]"));
                    self.line(format!("{c_ty} {} = {value};", mangle(&ident.name)));
                }
                let v = self.block(body);
                self.line(format!("(void)({v});"));
                self.depth -= 1;
                self.line("}");
            }
            StmtKind::While { cond, body } => {
                // The condition is re-evaluated each pass, so its statements
                // have to live inside the loop.
                self.line("while (1) {");
                self.depth += 1;
                let c = self.expr(cond);
                self.line(format!("if (!({c})) break;"));
                let v = self.block(body);
                self.line(format!("(void)({v});"));
                self.depth -= 1;
                self.line("}");
            }
            StmtKind::Expr(e) => {
                let v = self.expr(e);
                self.line(format!("(void)({v});"));
            }
        }
    }

    // --- expressions -----------------------------------------------------

    /// Emit whatever statements `e` needs and return a C expression for it.
    fn expr(&mut self, e: &Expr) -> String {
        match &e.kind {
            ExprKind::Literal(lit) => self.literal(lit),
            ExprKind::Path(p) => {
                let Some(name) = p.as_single() else {
                    self.refuse(e.span, "a qualified path");
                    return "0".to_owned();
                };
                if let Some((owner, tag)) = self.variant_tags.get(&name.name) {
                    // A nullary constructor used as a value.
                    let value = format!(
                        "(vise_enum){{ .tag = VISE_TAG_{owner}_{}, .f = {{0}} }}",
                        name.name
                    );
                    let _ = tag;
                    return value;
                }
                if name.name == "Unit" {
                    return "0".to_owned();
                }
                mangle(&name.name)
            }
            ExprKind::Call { callee, args } => self.call(e, callee, args),
            ExprKind::Field { base, name } => {
                let b = self.expr(base);
                format!("({b}).{}", mangle(&name.name))
            }
            ExprKind::Index { base, index } => {
                let b = self.expr(base);
                let i = self.expr(index);
                let element = element_type(&self.type_of(base));
                let c_ty = self.c_type(&element);
                let member = self.slot_member(&element);
                unpack(&c_ty, member, &format!("vise_list_get({b}, {i})"))
            }
            ExprKind::Unary { op, operand } => {
                let v = self.expr(operand);
                match op {
                    UnOp::Not => format!("(!({v}))"),
                    UnOp::Neg => {
                        if matches!(self.type_of(operand), Ty::Con(ref n, _) if n == "Float") {
                            format!("(-({v}))")
                        } else {
                            format!("vise_neg({v})")
                        }
                    }
                }
            }
            ExprKind::Binary { op, lhs, rhs } => self.binary(*op, lhs, rhs),
            ExprKind::Try(inner) => self.try_expr(e, inner),
            ExprKind::If {
                cond,
                then,
                otherwise,
            } => self.if_expr(e, cond, then, otherwise),
            ExprKind::Match { scrutinee, arms } => self.match_expr(e, scrutinee, arms),
            ExprKind::Block(b) => {
                let (lines, value) = self.capture(|s| s.block(b));
                self.lines.extend(lines);
                value
            }
            ExprKind::RecordLit { name, fields } => {
                let mut parts = Vec::new();
                for f in fields {
                    let v = self.expr(&f.value);
                    parts.push(format!(".{} = {v}", mangle(&f.name.name)));
                }
                format!("(vise_rec_{}){{ {} }}", name.name, parts.join(", "))
            }
            ExprKind::ListLit(items) => {
                let element = element_type(&self.type_of(e));
                let member = self.slot_member(&element);
                let list = self.temp();
                self.line(format!(
                    "vise_list {list} = vise_list_new({});",
                    items.len()
                ));
                for (i, item) in items.iter().enumerate() {
                    let v = self.expr(item);
                    let packed = self.pack(&element, &v);
                    self.line(format!("{list}.items[{i}].{member} = {packed};"));
                }
                list
            }
            ExprKind::Return(value) => {
                let v = match value {
                    Some(v) => self.expr(v),
                    None => "0".to_owned(),
                };
                // A bare `return` in a Unit function has nothing to hand back.
                if value.is_some() {
                    self.line(format!("return {v};"));
                } else {
                    self.line("return;");
                }
                "0".to_owned()
            }
            ExprKind::Break => {
                self.line("break;");
                "0".to_owned()
            }
            ExprKind::Continue => {
                self.line("continue;");
                "0".to_owned()
            }
            // A borrow is transparent: values are immutable, so the borrow and
            // its referent lower to the same thing.
            ExprKind::Borrow { operand, .. } => self.expr(operand),
            ExprKind::MethodCall {
                receiver,
                method,
                args,
            } => {
                let value = self.expr(receiver);
                for a in args {
                    self.expr(a);
                }
                if method.name == "clone" && args.is_empty() {
                    // Values are immutable, so a clone is the value itself.
                    value
                } else {
                    self.refuse(e.span, "a method other than `.clone()`");
                    "0".to_owned()
                }
            }
        }
    }

    fn literal(&mut self, lit: &Literal) -> String {
        match lit {
            Literal::Int(v) => format!("INT64_C({v})"),
            Literal::Float(text) => {
                if text.contains('.') {
                    text.clone()
                } else {
                    format!("{text}.0")
                }
            }
            Literal::Bool(v) => (*v).to_string(),
            Literal::Char(c) => format!("{}u", *c as u32),
            Literal::Str(parts) => self.string(parts),
        }
    }

    /// Build a string from its literal pieces and interpolations.
    fn string(&mut self, parts: &[StrPart]) -> String {
        let mut pieces: Vec<String> = Vec::new();
        for part in parts {
            match part {
                StrPart::Text(text) => {
                    pieces.push(format!(
                        "vise_str_literal({}, {})",
                        c_string(text),
                        text.len()
                    ));
                }
                StrPart::Interpolation(e) => {
                    let v = self.expr(e);
                    let ty = self.type_of(e);
                    let converter = match self.c_type(&ty).as_str() {
                        "vise_str" => None,
                        "double" => Some("vise_str_from_float"),
                        "bool" => Some("vise_str_from_bool"),
                        "uint32_t" => Some("vise_str_from_char"),
                        "int64_t" => Some("vise_str_from_int"),
                        _ => {
                            self.refuse(e.span, "interpolating a compound value");
                            None
                        }
                    };
                    pieces.push(match converter {
                        Some(f) => format!("{f}({v})"),
                        None => v,
                    });
                }
            }
        }
        match pieces.len() {
            0 => "vise_str_literal(\"\", 0)".to_owned(),
            1 => pieces.pop().expect("one piece"),
            _ => pieces
                .into_iter()
                .reduce(|a, b| format!("vise_str_concat({a}, {b})"))
                .expect("at least two"),
        }
    }

    fn binary(&mut self, op: BinOp, lhs: &Expr, rhs: &Expr) -> String {
        // Short-circuit operators must not evaluate the right side eagerly, and
        // emitting its statements before the branch would do exactly that.
        if matches!(op, BinOp::And | BinOp::Or) {
            let l = self.expr(lhs);
            let result = self.temp();
            self.line(format!("bool {result} = {l};"));
            let test = if op == BinOp::And {
                result.clone()
            } else {
                format!("!{result}")
            };
            self.line(format!("if ({test}) {{"));
            self.depth += 1;
            let r = self.expr(rhs);
            self.line(format!("{result} = {r};"));
            self.depth -= 1;
            self.line("}");
            return result;
        }

        let l = self.expr(lhs);
        let r = self.expr(rhs);
        let ty = self.type_of(lhs);
        let is_str = matches!(self.c_type(&ty).as_str(), "vise_str");
        let is_float = matches!(self.c_type(&ty).as_str(), "double");

        match op {
            BinOp::Eq if is_str => format!("vise_str_eq({l}, {r})"),
            BinOp::Ne if is_str => format!("(!vise_str_eq({l}, {r}))"),
            BinOp::Lt if is_str => format!("(vise_str_cmp({l}, {r}) < 0)"),
            BinOp::Le if is_str => format!("(vise_str_cmp({l}, {r}) <= 0)"),
            BinOp::Gt if is_str => format!("(vise_str_cmp({l}, {r}) > 0)"),
            BinOp::Ge if is_str => format!("(vise_str_cmp({l}, {r}) >= 0)"),
            BinOp::Eq => format!("(({l}) == ({r}))"),
            BinOp::Ne => format!("(({l}) != ({r}))"),
            BinOp::Lt => format!("(({l}) < ({r}))"),
            BinOp::Le => format!("(({l}) <= ({r}))"),
            BinOp::Gt => format!("(({l}) > ({r}))"),
            BinOp::Ge => format!("(({l}) >= ({r}))"),
            // §4: integer arithmetic traps. Floats follow IEEE-754 instead.
            _ if is_float => {
                let c = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    _ => "+",
                };
                format!("(({l}) {c} ({r}))")
            }
            BinOp::Add => format!("vise_add({l}, {r})"),
            BinOp::Sub => format!("vise_sub({l}, {r})"),
            BinOp::Mul => format!("vise_mul({l}, {r})"),
            BinOp::Div => format!("vise_div({l}, {r})"),
            BinOp::Rem => format!("vise_rem({l}, {r})"),
            BinOp::And | BinOp::Or => unreachable!("handled above"),
        }
    }

    fn call(&mut self, whole: &Expr, callee: &Expr, args: &[Expr]) -> String {
        let ExprKind::Path(path) = &callee.kind else {
            self.refuse(whole.span, "calling a computed value");
            return "0".to_owned();
        };
        let Some(name) = path.as_single() else {
            self.refuse(whole.span, "a qualified call");
            return "0".to_owned();
        };

        let mut values = Vec::new();
        for a in args {
            values.push(self.expr(a));
        }

        if vise_check::builtin(&name.name).is_some() {
            return self.builtin(&name.name, &values, args);
        }

        if let Some((owner, _)) = self.variant_tags.get(&name.name).cloned() {
            // Built as statements rather than as one compound literal: a wide
            // field is stored with `memcpy`, which is not an initialiser.
            let built = self.temp();
            self.line(format!("vise_enum {built};"));
            self.line(format!("memset(&{built}, 0, sizeof {built});"));
            self.line(format!("{built}.tag = VISE_TAG_{owner}_{};", name.name));
            let subject = self.type_of(whole);
            for (i, (value, arg)) in values.iter().zip(args).enumerate() {
                let declared = self.payload_type(&name.name, i, &subject);
                // A generic built-in payload can be unknown here; the argument
                // is then the better authority on its own type.
                let ty = if matches!(declared, Ty::Error) {
                    self.type_of(arg)
                } else {
                    declared
                };
                let offset = self.field_slot(&name.name, i, &subject);
                self.store_field(&built, offset, &ty, value);
            }
            return built;
        }

        if !self.functions.contains_key(&name.name) {
            self.refuse(whole.span, "a call to an imported function");
            return "0".to_owned();
        }
        format!("vise_fn_{}({})", mangle(&name.name), values.join(", "))
    }

    /// Lower a `core` call.
    ///
    /// Most are a direct call into `runtime/c/value.c`. Two are not: `append`
    /// and `at` are generic, so the element's slot member is only known here,
    /// where the checker's type map is to hand.
    fn builtin(&mut self, name: &str, values: &[String], args: &[Expr]) -> String {
        let arg = |i: usize| values.get(i).cloned().unwrap_or_else(|| "0".to_owned());

        match name {
            "print" => {
                self.line(format!("vise_print({});", arg(0)));
                "0".to_owned()
            }
            "exit" => {
                self.line(format!("vise_exit({});", arg(0)));
                "0".to_owned()
            }

            "length" => format!("(({}).len)", arg(0)),
            "append" => {
                let element = args.get(1).map_or(Ty::Error, |a| self.type_of(a));
                let member = self.slot_member(&element);
                let packed = self.pack(&element, &arg(1));
                format!(
                    "vise_list_append({}, (vise_slot){{ .{member} = {packed} }})",
                    arg(0)
                )
            }
            "at" => {
                // `Option<T>`: the payload slot is read back as T, which only
                // this pass knows.
                let element = args
                    .first()
                    .map_or(Ty::Error, |a| element_type(&self.type_of(a)));
                let list = self.temp();
                let index = self.temp();
                let result = self.temp();
                self.line(format!("vise_list {list} = {};", arg(0)));
                self.line(format!("int64_t {index} = {};", arg(1)));
                self.line(format!("vise_enum {result};"));
                self.line(format!("if ({index} >= 0 && {index} < {list}.len) {{"));
                self.depth += 1;
                self.line(format!("{result} = (vise_enum){{ .tag = VISE_TAG_SOME }};"));
                // A list slot is one slot wide whatever it holds, so a wide
                // element arrives boxed and has to be unpacked before it can go
                // into the payload, which spreads it instead.
                let c_ty = self.c_type(&element);
                let member = self.slot_member(&element);
                let value = unpack(&c_ty, member, &format!("{list}.items[{index}]"));
                self.store_field(&result, 0, &element, &value);
                self.depth -= 1;
                self.line("} else {");
                self.depth += 1;
                self.line(format!("{result} = (vise_enum){{ .tag = VISE_TAG_NONE }};"));
                self.depth -= 1;
                self.line("}");
                result
            }

            "str_length" => format!("vise_str_length({})", arg(0)),
            "lines" => format!("vise_lines({})", arg(0)),
            "split" => format!("vise_split({}, {})", arg(0), arg(1)),
            "join" => format!("vise_join({}, {})", arg(0), arg(1)),
            "starts_with" => format!("vise_starts_with({}, {})", arg(0), arg(1)),
            "contains" => format!("vise_contains({}, {})", arg(0), arg(1)),
            "parse_int" => format!("vise_parse_int({})", arg(0)),

            "read_file" => format!("vise_read_file({})", arg(0)),
            "write_file" => format!("vise_write_file({}, {})", arg(0), arg(1)),
            "list_dir" => format!("vise_list_dir({})", arg(0)),
            "is_dir" => format!("vise_is_dir({})", arg(0)),
            "file_size" => format!("vise_file_size({})", arg(0)),

            "args" => "vise_args()".to_owned(),
            "now" => "vise_now()".to_owned(),

            other => {
                self.unsupported.push(
                    Diagnostic::error(
                        Code::UnexpectedToken,
                        Span::new(vise_diag::FileId(0), 0, 0),
                        format!("`{other}` is in core but the backend does not lower it"),
                    )
                    .with_note("`vise run` interprets the same program without this restriction"),
                );
                "0".to_owned()
            }
        }
    }

    fn try_expr(&mut self, whole: &Expr, inner: &Expr) -> String {
        let v = self.expr(inner);
        let subject = self.temp();
        let result = self.temp();
        let ty = self.type_of(whole);
        let c_ty = self.c_type(&ty);

        self.line(format!("vise_enum {subject} = {v};"));
        self.line(format!(
            "if ({subject}.tag == VISE_TAG_Result_Err) return {subject};"
        ));
        let unpacked = self.load_field(&subject, 0, &ty);
        self.line(format!("{c_ty} {result} = {unpacked};"));
        result
    }

    fn if_expr(&mut self, whole: &Expr, cond: &Expr, then: &Block, otherwise: &Expr) -> String {
        let c = self.expr(cond);
        let result = self.temp();
        let c_ty = self.c_type(&self.type_of(whole));
        self.line(format!("{c_ty} {result};"));
        self.line(format!("if ({c}) {{"));

        self.depth += 1;
        let (lines, value) = self.capture(|s| s.block(then));
        self.lines.extend(lines);
        self.line(format!("{result} = {value};"));
        self.depth -= 1;

        self.line("} else {");
        self.depth += 1;
        let (lines, value) = self.capture(|s| s.expr(otherwise));
        self.lines.extend(lines);
        self.line(format!("{result} = {value};"));
        self.depth -= 1;
        self.line("}");
        result
    }

    fn match_expr(
        &mut self,
        whole: &Expr,
        scrutinee: &Expr,
        arms: &[vise_ast::MatchArm],
    ) -> String {
        let subject_value = self.expr(scrutinee);
        let subject = self.temp();
        let subject_ty = self.type_of(scrutinee);
        let subject_c = self.c_type(&subject_ty);
        self.line(format!("{subject_c} {subject} = {subject_value};"));

        let result = self.temp();
        let c_ty = self.c_type(&self.type_of(whole));
        self.line(format!("{c_ty} {result};"));

        let mut first = true;
        for arm in arms {
            let condition = self.pattern_test(&arm.pattern, &subject, &subject_ty);
            let keyword = if first { "if" } else { "} else if" };
            first = false;
            self.line(format!("{keyword} ({condition}) {{"));
            self.depth += 1;
            self.bind_pattern(&arm.pattern, &subject, &subject_ty);
            let (lines, value) = self.capture(|s| s.expr(&arm.body));
            self.lines.extend(lines);
            self.line(format!("{result} = {value};"));
            self.depth -= 1;
        }
        if first {
            self.refuse(whole.span, "a match with no arms");
            return "0".to_owned();
        }
        self.line("} else {");
        self.depth += 1;
        // The checker proves exhaustiveness, so this is unreachable; C does not
        // know that, and a missing assignment would be undefined behaviour.
        self.line("vise_trap(\"no match arm applied\");");
        self.depth -= 1;
        self.line("}");
        result
    }

    /// A C condition that is true when `pattern` matches `subject`.
    fn pattern_test(&mut self, pattern: &Pattern, subject: &str, ty: &Ty) -> String {
        match &pattern.kind {
            PatternKind::Wildcard | PatternKind::Binding(_) => "1".to_owned(),
            PatternKind::Literal(lit) => {
                let v = self.literal(lit);
                if matches!(self.c_type(ty).as_str(), "vise_str") {
                    format!("vise_str_eq({subject}, {v})")
                } else {
                    format!("({subject} == {v})")
                }
            }
            PatternKind::Variant { path, fields } => {
                let Some(name) = path.as_single() else {
                    return "0".to_owned();
                };
                let Some((owner, _)) = self.variant_tags.get(&name.name).cloned() else {
                    return "0".to_owned();
                };
                let mut test = format!("{subject}.tag == VISE_TAG_{owner}_{}", name.name);
                for (i, sub) in fields.iter().enumerate() {
                    // Only a nested constructor needs a further test; a binding
                    // or wildcard always matches.
                    if let PatternKind::Variant { .. } | PatternKind::Literal(_) = &sub.kind {
                        let payload = self.payload_type(&name.name, i, ty);
                        let c_ty = self.c_type(&payload);
                        let offset = self.field_slot(&name.name, i, ty);
                        let inner = self.load_field(subject, offset, &payload);
                        let nested = self.temp();
                        self.line(format!("{c_ty} {nested} = ({subject}.tag == VISE_TAG_{owner}_{}) ? {inner} : ({c_ty}){{0}};", name.name));
                        let sub_test = self.pattern_test(sub, &nested, &payload);
                        let _ = write!(test, " && ({sub_test})");
                    }
                }
                format!("({test})")
            }
        }
    }

    /// Declare whatever `pattern` binds, given that it matched.
    fn bind_pattern(&mut self, pattern: &Pattern, subject: &str, ty: &Ty) {
        match &pattern.kind {
            PatternKind::Wildcard | PatternKind::Literal(_) => {}
            PatternKind::Binding(ident) => {
                let c_ty = self.c_type(ty);
                self.line(format!("{c_ty} {} = {subject};", mangle(&ident.name)));
            }
            PatternKind::Variant { path, fields } => {
                let Some(name) = path.as_single() else { return };
                for (i, sub) in fields.iter().enumerate() {
                    let payload = self.payload_type(&name.name, i, ty);
                    let c_ty = self.c_type(&payload);
                    let offset = self.field_slot(&name.name, i, ty);
                    let value = self.load_field(subject, offset, &payload);
                    let slot = self.temp();
                    self.line(format!("{c_ty} {slot} = {value};"));
                    self.bind_pattern(sub, &slot, &payload);
                }
            }
        }
    }

    /// The type of a variant's field.
    ///
    /// A user variant declares its fields, so the table has them. A built-in
    /// does not: `Ok`'s payload is whatever `T` is in the `Result<T, E>` being
    /// matched, which is only knowable from the value under inspection.
    fn payload_type(&self, variant: &str, index: usize, subject: &Ty) -> Ty {
        let from_subject = |i: usize| match subject {
            Ty::Con(_, args) => args.get(i).cloned().unwrap_or(Ty::Error),
            _ => Ty::Error,
        };
        match variant {
            "Ok" | "Some" => from_subject(0),
            "Err" => from_subject(1),
            _ => self
                .variant_payloads
                .get(variant)
                .and_then(|f| f.get(index))
                .cloned()
                .unwrap_or(Ty::Error),
        }
    }
}

/// The element type of a `List<T>`.
fn element_type(ty: &Ty) -> Ty {
    match ty {
        Ty::Con(name, args) if name == "List" || name == "Set" => {
            args.first().cloned().unwrap_or(Ty::Error)
        }
        Ty::Ref { inner, .. } => element_type(inner),
        _ => Ty::Error,
    }
}

/// Read a value out of an enum payload or list slot.
fn unpack(c_type: &str, member: &str, slot: &str) -> String {
    if member == "as_ptr" {
        format!("(*({c_type} *)({slot}).as_ptr)")
    } else {
        format!("({slot}).{member}")
    }
}

/// Prefix names so a Vise identifier can never collide with a C keyword.
fn mangle(name: &str) -> String {
    format!("v_{name}")
}

/// Render a Rust string as a C string literal.
fn c_string(text: &str) -> String {
    let mut out = String::from("\"");
    for byte in text.bytes() {
        match byte {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\t' => out.push_str("\\t"),
            b'\r' => out.push_str("\\r"),
            0x20..=0x7e => out.push(byte as char),
            other => {
                let _ = write!(out, "\\{other:03o}");
            }
        }
    }
    out.push('"');
    out
}

/// Convert an AST type to a checker type.
fn ty_of(t: &vise_ast::Type) -> Ty {
    match &t.kind {
        vise_ast::TypeKind::Unit => Ty::unit(),
        vise_ast::TypeKind::Ref { inner, .. } => ty_of(inner),
        vise_ast::TypeKind::Named { name, args } => {
            Ty::Con(name.name.clone(), args.iter().map(ty_of).collect())
        }
    }
}

/// Unused import guard: `Effect` is re-exported for callers that inspect a
/// module's effects before deciding how to confine the built program.
#[doc(hidden)]
pub fn _effects_are_reexported(_: Effect) {}
