[package]
name = "vise-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "vise"
path = "src/main.rs"

[dependencies]
vise-diag.workspace = true
vise-lex.workspace = true
vise-ast.workspace = true
vise-parse.workspace = true
vise-check.workspace = true
vise-ir.workspace = true
vise-codegen.workspace = true

[lints]
workspace = true
